version: "3.4"

services:
  mssql:
    build: ./db
    container_name: fds-azuresql
    environment:
      MSSQL_SA_PASSWORD: "MssqlPass123"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"

  # client:
  #   container_name: fds-client
  #   build: ./client
  #   environment:
  #     - "FDS_API_URL=http://localhost:6401"
  #   ports:
  #     - "3001:3000"

  rabbitmq:
    container_name: fds-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      "RABBITMQ_DEFAULT_PASS": "rabbitmqpass123"
    ports:
      - "4369:4369"
      - "5671-5672:5671-5672"
      - "15672:15672"
      - "25672:25672"

  api:
    container_name: fds-api
    build:
      context: .
      dockerfile: ./server/src/FDS.Api/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:6401"
      - "ConnectionStrings__DefaultConnection=user id=sa;password=MssqlPass123;data source=mssql;initial catalog=FDS;Connect Timeout=30;Pooling=true;"
      - "RabbitMQ__Address=rabbitmq"
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - 6401:6401

  worker:
    container_name: fds-worker
    build:
      context: .
      dockerfile: ./server/src/Services/FDS.Update.Service/Dockerfile
    volumes:
      - ./package.json:/appdata/package.json
      # - /usr/local/bin/:/usr/local/bin/
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:6501"
      - "ConnectionStrings__DefaultConnection=user id=sa;password=MssqlPass123;data source=mssql;initial catalog=FDS;Connect Timeout=30;Pooling=true;"
      - "RabbitMQ__Address=rabbitmq"
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - 6501:6501
